#!/bin/bash

[colors]
purple = #AB9DF2
black = #2F3D44
white = #dfdfdf
transparent = #00000000

background = #2F3D44
foreground = #1ABC9C
primary = #2F3D44
secondary = #FC9867
alert = #bd2c40

[module/i3]
type = internal/i3
pin-workspaces = true
index-sort = true

# focused = Active workspace on focused monitor
label-focused = %index%
label-focused-foreground = #1ABC9C
label-focused-padding = 1

# unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-background = #2F3D44
label-unfocused-padding = 1

[module/cpu]
type = internal/cpu

interval = 2

format-padding = 0

label = "%percentage:2%%"

[module/battery]
type = internal/battery

# This is useful in case the battery never reports 100% charge
full-at = 100

battery = BAT0
adapter = ADP1

poll-interval = 5

format-charging = <animation-charging> <label-charging>

format-discharging = <ramp-capacity> <label-discharging>

label-charging = %percentage%%

label-discharging = %percentage%%

label-full = 

ramp-capacity-0 = %{F#ff0000}
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

bar-capacity-width = 10

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 

animation-charging-framerate = 750

[module/cputemp]
type = custom/script
exec = sensors | grep Tctl | tr -d "+" | awk '{print $2}'
interval = 1
label = "🌡 %output%"

[module/date]
type = internal/date

interval = 1.0

#format
date = %Y-%m-%d%
time = %I:%M %p
time-alt = %a %b %d
format-foreground = ${colors.foreground}

label = %time%
format = <label>

time-format = %H:%M

[bar/theme]
monitor-strict = false

width = 100%
height = 25
bottom = false
fixed-center = true

background = #2F3D44

font-0 = Cascadia Code:pixelsize=12;4
font-1 = FontAwesome 6 Free:style=Regular:size=10;4
font-2 = FontAwesome 6 Free:style=Solid:size=10;4
font-3 = FontAwesome 6 Brands:style=Solid:size=10;4

padding = 3
module-margin = 1

modules-left = i3
modules-center = date
modules-right = battery cputemp cpu 
tray-position = right
