CREATE VIEW TopDomainsByVisits as
select max(id), max(title) t, max(url) m, sum(visit_count) v, domain
from  urls
      where domain in
            ('pornsos.com', 'bing.com', 'xhamster.com', 'google.com', 'xvideos.com', 'nudevista.com', 'youporn.com',
             'google.se', 'pornhub.com', 'proporn.com', 'rule34.paheal.net', 'pervertslut.com', 'yeptube.com',
             'gotporn.com', 'tnaflix.com', 'mrstiff.com', 'motherless.com', 'xnxx.com', 'bravotube.net',
             'bestialitytaboo.tv', 'gaybeast.com', 'xxxpornclips.pro', 'femefun.com', 'tube8.com', 'en.luxuretv.com',
             'mylust.com', 'anyporn.com', '3animalsextube.com', 'boobpedia.com', 'nuvid.com', 'xxxbunker.com',
             'hclips.com', 'empflix.com', 'fapporn.me', 'tubemonsoon.com', 'pornvideotop.com', 'chikiporn.com',
             'viptube.com', 'iceporn.com', 'redtube.com', 'txxx.com', 'hiswifeslut.com', 'pornfay.org', 'qdick.com',
             'jizzbunker.com', 'xxxdan.com', '4hen.net', 'homemadecuckold.com', 'zooskoolvideos.com', 'mrsnake.com',
             'wifefuckstranger.com', 'zoomobileporn.com', 'mywifefucked.com', 'dohomemadeporn.com', 'supertubeporn.com',
             'amateurinterracialporn.com', 'club300.se', 'cuckoldplacetube.com', 'eporner.com', 'forumophilia.com',
             'hnntube.com', 'milfporn8.com', 'sex3.com', 'sunporno.com', 'yuvutu.com', 'esmatube.com', 'bbcwives.com',
             'h2porn.com', 'hotntubes.com', 'imagefap.com', 'videosz.com', 'maturell.com', 'wifelovesblacks.com',
             'ah-me.com', 'analdin.com', 'grannysex.in', 'maturewifeshare.com', 'porn.com', 'pornspark.com',
             'trueamateurmodels.com', 'upornia.com', 'video.nudevista.com', 'cuckoldsoul.com', 'homemoviestube.com',
             'keezmovies.com', 'pornomovies.com', 'tubepornclassic.com', 'dobbyporn.com', 'goldporntube.com',
             'nesaporn.com', 'zoo.cab', 'bbwfuckpic.com', 'porntubest.com', 'spankbang.com', 'thumbzilla.com',
             'vintagevideos.xxx', 'cuckoldporn.pro', 'darkpanthera.com', 'eroprofile.com', 'hotpornshow.com',
             'ixxx.com', 'mature-cuckold.com', 'mixxporn.com', 'redditcuckold.com', 'tube1st.com', 'webpornhub.com',
             'allpornovideo.com', 'azgals.com', 'blackfuckwife.com', 'desihoes.com', 'freeones.se', 'rudenude.com',
             'wifegoblack.com', 'allpornotube.com', 'amateursfuckporn.com', 'amateurwifeshared.com', 'anysex.com',
             'ebonyinlove.com', 'erkiss.org', 'igrushkimakushki.ru', 'innowacyjnafirma.info', 'mmmature.com',
             'tube2017.com', 'vidsvidsvids.com', 'wifecuckoldme.com', 'xozilla.com', 'zootube365.com',
             'african-women.net', 'allpornmature.com', 'alohatube.com', 'animalsexfun.com', 'board.freeones.com',
             'fuskator.com', 'galleries.adult-empire.com', 'pbs-0.adult-empire.com', 'porntube247.com',
             'wifeblackfuckers.com', 'xxxdinotube.com', 'amateurfetishist.com', 'datawav.club', 'desixnxx.net',
             'dirtydoglinks.com', 'fanaken.com', 'freepornjpg.com', 'freshxxxtube.com', 'girlzwelike.com',
             'grannysex-tubes.com', 'jeanswing.com', 'pbs-2.adult-empire.com', 'postyourhairypussy.com',
             'rodneymoore.com', 'tubegalore.com', 'wifesharingporn.com', 'yuppix.com', 'anyporn.org',
             'breedingmoms.com', 'cuckold69.com', 'e-hentai.org', 'fotoscaserasx.com', 'galleries2.adult-empire.com',
             'hardsextube.com', 'heavy-r.com', 'largeporntube.com', 'matureanalfucks.com', 'maturetubefuck.com',
             'myzoowife.com', 'pornerbros.com', 'topmatureporntube.com', 'vintagecuties.com', 'xrares.com',
             'xvideo.site', 'xxxwifevideos.com', 'zootube1.com', 'badjojo.com', 'bestfreetube.xxx', 'electsex.com',
             'excaliburfilms.com', 'findtubes.com', 'fitgirlsohyeah.tumblr.com', 'gfycat.com', 'hotmaturefilm.com',
             'hotmilfs.pics', 'hotsexyaunty.com', 'maturesexvideos.tv', 'matureshock.com', 'my.freeones.com',
             'youjizz.com', 'youngheaven.com', 'zoo.xxx', 'aporntv.com', 'blackcockhunger.com', 'blog.youporn.com',
             'caramelmilf.com', 'creampietubeporn.com', 'cuckold-moms.com', 'fr.xhamster.com', 'galleries.mrpov.com',
             'hotgrannypics.com', 'hottubeclips.com', 'iafd.com', 'ircuckporn.com', 'letmejerk.com', 'milffox.com',
             'myfreeblack.com', 'naomi1.net', 'oopsmovs.com', 'pichunter.com', 'realgfporn.com', 'realmaturetube.pro',
             'rexxx.org', 'spazkid.newgrounds.com', 'trinity-productions.com', 'tubezzz.net', 'wifeporn.pro',
             'xxxlibz.com', '16honeys.com', 'amateurfatbbw.com', 'amateurporntape.com', 'anybunny.com',
             'askauntylisa.com', 'b2wblog.com', 'bestcuckoldporn.com', 'bigbuttlinks.com', 'bigcamtube.com',
             'britishbukkakebabes.com', 'cuckold-husbands.net', 'cuckoldwifesex.com', 'desixxxpics.com',
             'dogsex.stream', 'embedy.cc', 'f1ix.com', 'fatalfemdoms.com', 'freefuckvidz.com', 'hdsex.org',
             'momder.com', 'perfectgirls.net', 'porngo.com', 'see.xxx', 'xxxdessert.com', 'xxxtubezoo.com',
             '66.media.tumblr.com', 'bangyoulater.net', 'bestialitysexvideos.com', 'bubbaporn.com', 'cec18.com',
             'community.whattoexpect.com', 'confessionpost.com', 'deviants.com', 'e621.net', 'fantasti.cc',
             'fapdig.com', 'flashback.org', 'frag-den-doc.de', 'fromme-lisa.blogspot.com', 'fuckedhomemade.com',
             'grannyinlove.com', 'guinyfimez.wixsite.com', 'homemadenet.com', 'hotgoo.com', 'iporntv.net',
             'ourhealth.com', 'pervclips.com', 'pornpics.com', 'qcock.com', 'elitesmothering.com', 'femjoy.com',
             'imgur.com', 'oko.gnesin-hanty.ru')
group by domain
order by v desc, domain;

