Remove-Item alias:?          -Force -ErrorAction SilentlyContinue
Remove-Item alias:%          -Force -ErrorAction SilentlyContinue
Remove-Item alias:ac         -Force -ErrorAction SilentlyContinue
Remove-Item alias:asnp       -Force -ErrorAction SilentlyContinue
Remove-Item alias:cat        -Force -ErrorAction SilentlyContinue
Remove-Item alias:cd         -Force -ErrorAction SilentlyContinue
Remove-Item alias:cfs        -Force -ErrorAction SilentlyContinue
Remove-Item alias:chdir      -Force -ErrorAction SilentlyContinue
Remove-Item alias:clc        -Force -ErrorAction SilentlyContinue
Remove-Item alias:clear      -Force -ErrorAction SilentlyContinue
Remove-Item alias:clhy       -Force -ErrorAction SilentlyContinue
Remove-Item alias:cli        -Force -ErrorAction SilentlyContinue
Remove-Item alias:clp        -Force -ErrorAction SilentlyContinue
Remove-Item alias:cls        -Force -ErrorAction SilentlyContinue
Remove-Item alias:clv        -Force -ErrorAction SilentlyContinue
Remove-Item alias:cnsn       -Force -ErrorAction SilentlyContinue
Remove-Item alias:compare    -Force -ErrorAction SilentlyContinue
Remove-Item alias:copy       -Force -ErrorAction SilentlyContinue
Remove-Item alias:cp         -Force -ErrorAction SilentlyContinue
Remove-Item alias:cpi        -Force -ErrorAction SilentlyContinue
Remove-Item alias:cpp        -Force -ErrorAction SilentlyContinue
Remove-Item alias:curl       -Force -ErrorAction SilentlyContinue
Remove-Item alias:cvpa       -Force -ErrorAction SilentlyContinue
Remove-Item alias:dbp        -Force -ErrorAction SilentlyContinue
Remove-Item alias:del        -Force -ErrorAction SilentlyContinue
Remove-Item alias:diff       -Force -ErrorAction SilentlyContinue
Remove-Item alias:dir        -Force -ErrorAction SilentlyContinue
Remove-Item alias:dnsn       -Force -ErrorAction SilentlyContinue
Remove-Item alias:ebp        -Force -ErrorAction SilentlyContinue
Remove-Item alias:echo       -Force -ErrorAction SilentlyContinue
Remove-Item alias:epal       -Force -ErrorAction SilentlyContinue
Remove-Item alias:epcsv      -Force -ErrorAction SilentlyContinue
Remove-Item alias:epsn       -Force -ErrorAction SilentlyContinue
Remove-Item alias:erase      -Force -ErrorAction SilentlyContinue
Remove-Item alias:etsn       -Force -ErrorAction SilentlyContinue
Remove-Item alias:exsn       -Force -ErrorAction SilentlyContinue
Remove-Item alias:fc         -Force -ErrorAction SilentlyContinue
Remove-Item alias:fhx        -Force -ErrorAction SilentlyContinue
Remove-Item alias:fl         -Force -ErrorAction SilentlyContinue
Remove-Item alias:foreach    -Force -ErrorAction SilentlyContinue
Remove-Item alias:ft         -Force -ErrorAction SilentlyContinue
Remove-Item alias:fw         -Force -ErrorAction SilentlyContinue
Remove-Item alias:gal        -Force -ErrorAction SilentlyContinue
Remove-Item alias:gbp        -Force -ErrorAction SilentlyContinue
Remove-Item alias:gc         -Force -ErrorAction SilentlyContinue
Remove-Item alias:gcb        -Force -ErrorAction SilentlyContinue
Remove-Item alias:gci        -Force -ErrorAction SilentlyContinue
Remove-Item alias:gcm        -Force -ErrorAction SilentlyContinue
Remove-Item alias:gcs        -Force -ErrorAction SilentlyContinue
Remove-Item alias:gdr        -Force -ErrorAction SilentlyContinue
Remove-Item alias:ghy        -Force -ErrorAction SilentlyContinue
Remove-Item alias:gi         -Force -ErrorAction SilentlyContinue
Remove-Item alias:gin        -Force -ErrorAction SilentlyContinue
Remove-Item alias:gjb        -Force -ErrorAction SilentlyContinue
Remove-Item alias:gl         -Force -ErrorAction SilentlyContinue
Remove-Item alias:gm         -Force -ErrorAction SilentlyContinue
Remove-Item alias:gmo        -Force -ErrorAction SilentlyContinue
Remove-Item alias:gp         -Force -ErrorAction SilentlyContinue
Remove-Item alias:gps        -Force -ErrorAction SilentlyContinue
Remove-Item alias:gpv        -Force -ErrorAction SilentlyContinue
Remove-Item alias:group      -Force -ErrorAction SilentlyContinue
Remove-Item alias:gsn        -Force -ErrorAction SilentlyContinue
Remove-Item alias:gsnp       -Force -ErrorAction SilentlyContinue
Remove-Item alias:gsv        -Force -ErrorAction SilentlyContinue
Remove-Item alias:gtz        -Force -ErrorAction SilentlyContinue
Remove-Item alias:gu         -Force -ErrorAction SilentlyContinue
Remove-Item alias:gv         -Force -ErrorAction SilentlyContinue
Remove-Item alias:gwmi       -Force -ErrorAction SilentlyContinue
Remove-Item alias:h          -Force -ErrorAction SilentlyContinue
Remove-Item alias:history    -Force -ErrorAction SilentlyContinue
Remove-Item alias:icm        -Force -ErrorAction SilentlyContinue
Remove-Item alias:iex        -Force -ErrorAction SilentlyContinue
Remove-Item alias:ihy        -Force -ErrorAction SilentlyContinue
Remove-Item alias:ii         -Force -ErrorAction SilentlyContinue
Remove-Item alias:ipal       -Force -ErrorAction SilentlyContinue
Remove-Item alias:ipcsv      -Force -ErrorAction SilentlyContinue
Remove-Item alias:ipmo       -Force -ErrorAction SilentlyContinue
Remove-Item alias:ipsn       -Force -ErrorAction SilentlyContinue
Remove-Item alias:irm        -Force -ErrorAction SilentlyContinue
Remove-Item alias:ise        -Force -ErrorAction SilentlyContinue
Remove-Item alias:iwmi       -Force -ErrorAction SilentlyContinue
Remove-Item alias:iwr        -Force -ErrorAction SilentlyContinue
Remove-Item alias:kill       -Force -ErrorAction SilentlyContinue
Remove-Item alias:lp         -Force -ErrorAction SilentlyContinue
Remove-Item alias:ls         -Force -ErrorAction SilentlyContinue
Remove-Item alias:man        -Force -ErrorAction SilentlyContinue
Remove-Item alias:md         -Force -ErrorAction SilentlyContinue
Remove-Item alias:measure    -Force -ErrorAction SilentlyContinue
Remove-Item alias:mi         -Force -ErrorAction SilentlyContinue
Remove-Item alias:mount      -Force -ErrorAction SilentlyContinue
Remove-Item alias:move       -Force -ErrorAction SilentlyContinue
Remove-Item alias:mp         -Force -ErrorAction SilentlyContinue
Remove-Item alias:mv         -Force -ErrorAction SilentlyContinue
Remove-Item alias:nal        -Force -ErrorAction SilentlyContinue
Remove-Item alias:ndr        -Force -ErrorAction SilentlyContinue
Remove-Item alias:ni         -Force -ErrorAction SilentlyContinue
Remove-Item alias:nmo        -Force -ErrorAction SilentlyContinue
Remove-Item alias:npssc      -Force -ErrorAction SilentlyContinue
Remove-Item alias:nsn        -Force -ErrorAction SilentlyContinue
Remove-Item alias:nv         -Force -ErrorAction SilentlyContinue
Remove-Item alias:ogv        -Force -ErrorAction SilentlyContinue
Remove-Item alias:oh         -Force -ErrorAction SilentlyContinue
Remove-Item alias:popd       -Force -ErrorAction SilentlyContinue
Remove-Item alias:ps         -Force -ErrorAction SilentlyContinue
Remove-Item alias:pushd      -Force -ErrorAction SilentlyContinue
Remove-Item alias:pwd        -Force -ErrorAction SilentlyContinue
Remove-Item alias:r          -Force -ErrorAction SilentlyContinue
Remove-Item alias:rbp        -Force -ErrorAction SilentlyContinue
Remove-Item alias:rcjb       -Force -ErrorAction SilentlyContinue
Remove-Item alias:rcsn       -Force -ErrorAction SilentlyContinue
Remove-Item alias:rd         -Force -ErrorAction SilentlyContinue
Remove-Item alias:rdr        -Force -ErrorAction SilentlyContinue
Remove-Item alias:ren        -Force -ErrorAction SilentlyContinue
Remove-Item alias:ri         -Force -ErrorAction SilentlyContinue
Remove-Item alias:rjb        -Force -ErrorAction SilentlyContinue
Remove-Item alias:rm         -Force -ErrorAction SilentlyContinue
Remove-Item alias:rmdir      -Force -ErrorAction SilentlyContinue
Remove-Item alias:rmo        -Force -ErrorAction SilentlyContinue
Remove-Item alias:rni        -Force -ErrorAction SilentlyContinue
Remove-Item alias:rnp        -Force -ErrorAction SilentlyContinue
Remove-Item alias:rp         -Force -ErrorAction SilentlyContinue
Remove-Item alias:rsn        -Force -ErrorAction SilentlyContinue
Remove-Item alias:rsnp       -Force -ErrorAction SilentlyContinue
Remove-Item alias:rujb       -Force -ErrorAction SilentlyContinue
Remove-Item alias:rv         -Force -ErrorAction SilentlyContinue
Remove-Item alias:rvpa       -Force -ErrorAction SilentlyContinue
Remove-Item alias:rwmi       -Force -ErrorAction SilentlyContinue
Remove-Item alias:sajb       -Force -ErrorAction SilentlyContinue
Remove-Item alias:sal        -Force -ErrorAction SilentlyContinue
Remove-Item alias:saps       -Force -ErrorAction SilentlyContinue
Remove-Item alias:sasv       -Force -ErrorAction SilentlyContinue
Remove-Item alias:sbp        -Force -ErrorAction SilentlyContinue
Remove-Item alias:sc         -Force -ErrorAction SilentlyContinue
Remove-Item alias:scb        -Force -ErrorAction SilentlyContinue
Remove-Item alias:select     -Force -ErrorAction SilentlyContinue
Remove-Item alias:set        -Force -ErrorAction SilentlyContinue
Remove-Item alias:shcm       -Force -ErrorAction SilentlyContinue
Remove-Item alias:si         -Force -ErrorAction SilentlyContinue
Remove-Item alias:sl         -Force -ErrorAction SilentlyContinue
Remove-Item alias:sleep      -Force -ErrorAction SilentlyContinue
Remove-Item alias:sls        -Force -ErrorAction SilentlyContinue
Remove-Item alias:sort       -Force -ErrorAction SilentlyContinue
Remove-Item alias:sp         -Force -ErrorAction SilentlyContinue
Remove-Item alias:spjb       -Force -ErrorAction SilentlyContinue
Remove-Item alias:spps       -Force -ErrorAction SilentlyContinue
Remove-Item alias:spsv       -Force -ErrorAction SilentlyContinue
Remove-Item alias:start      -Force -ErrorAction SilentlyContinue
Remove-Item alias:stz        -Force -ErrorAction SilentlyContinue
Remove-Item alias:sujb       -Force -ErrorAction SilentlyContinue
Remove-Item alias:sv         -Force -ErrorAction SilentlyContinue
Remove-Item alias:swmi       -Force -ErrorAction SilentlyContinue
Remove-Item alias:tee        -Force -ErrorAction SilentlyContinue
Remove-Item alias:trcm       -Force -ErrorAction SilentlyContinue
Remove-Item alias:type       -Force -ErrorAction SilentlyContinue
Remove-Item alias:wget       -Force -ErrorAction SilentlyContinue
Remove-Item alias:where      -Force -ErrorAction SilentlyContinue
Remove-Item alias:wjb        -Force -ErrorAction SilentlyContinue
Remove-Item alias:write      -Force -ErrorAction SilentlyContinue
